package com.example.backend.jobs;

public record Jobdetails(String aktuelleVeroeffentlichungsdatum,
                         String angebotsart,
                         String arbeitgeber,
                         String branchengruppe,
                         String branche,
                         String arbeitsorte,
                         String arbeitszeitmodelle,
                         String befristung,
                         String betriebsgroesse,
                         String eintrittsdatum,
                         String ersteVeroeffentlichungsdatum,
                         String allianzpartner,
                         String titel,
                         String beruf,
                         String stellenbeschreibung,
                         String anzahlOffeneStellen,
                         String arbeitgeberadresse,
                         String fertigkeiten,
                         String mobilitaet,
                         String arbeitgeberdarstellungUrl,
                         String verguetung ){}
